import { BoxDefinition } from './types';

export const CAREER_BOXES: BoxDefinition[] = [
  {
    boxNumber: 1,
    clusterTitleEn: "Agriculture, Food & Natural Resources",
    clusterTitleUr: "زراعت، خوراک اور قدرتی وسائل",
    colorScheme: "from-amber-600 to-emerald-700",
    descriptionEn: "Focuses on the production, processing, marketing, distribution, financing, and development of agricultural commodities and resources.",
    descriptionUr: "زرعی اجناس، خوراک، قدرتی وسائل اور ماحولیات کے تحفظ و پیداوار سے متعلق شعبہ۔",
    careerExamplesEn: ["Agricultural Engineer", "Veterinarian", "Environmental Scientist", "Farm Manager", "Food Technologist"],
    careerExamplesUr: ["زرعی انجینئر", "ماہر حیوانات (ویٹرنری)", "ماحولیاتی سائنسدان", "فارم منیجر", "فوڈ ٹیکنالوجسٹ"],
    activities: [
      { id: "b1_a1", en: "Learn how things grow and stay alive.", ur: "یہ سیکھنا کہ چیزیں کیسے اگتی اور زندہ رہتی ہیں۔" },
      { id: "b1_a2", en: "Make the best use of the earth's natural resources.", ur: "زمین کے قدرتی وسائل کا بہترین استعمال کرنا۔" },
      { id: "b1_a3", en: "Hunt and/or fish.", ur: "شکار کرنا یا مچھلی پکڑنا۔" },
      { id: "b1_a4", en: "Protect the environment.", ur: "ماحول کی حفاظت کرنا۔" },
      { id: "b1_a5", en: "Be outdoors in all kinds of weather.", ur: "ہر قسم کے موسم میں باہر رہنا۔" },
      { id: "b1_a6", en: "Plan, budget, and keep records.", ur: "منصوبہ بنانا، بجٹ بنانا اور ریکارڈ رکھنا۔" },
      { id: "b1_a7", en: "Operate machines and keep them in good repair.", ur: "مشینیں چلانا اور انہیں ٹھیک حالت میں رکھنا۔" },
    ],
    personalQualities: [
      { id: "b1_q1", en: "Self-reliant", ur: "خود انحصاری (اپنے کام خود کرنا)" },
      { id: "b1_q2", en: "Nature lover", ur: "فطرت سے محبت" },
      { id: "b1_q3", en: "Physically active", ur: "چاق و چوبند اور جسمانی طور پر فعال" },
      { id: "b1_q4", en: "Planner", ur: "منصوبہ بندی کی صلاحیت" },
      { id: "b1_q5", en: "Creative problem solver", ur: "مسائل کا تخلیقی حل نکالنے والا" },
    ],
    schoolSubjects: [
      { id: "b1_s1", en: "Math", ur: "ریاضی" },
      { id: "b1_s2", en: "Life Sciences (Biology)", ur: "حیاتیاتی علوم (بائیولوجی)" },
      { id: "b1_s3", en: "Earth Sciences", ur: "زمین کی سائنس (ارضیاتی علوم)" },
      { id: "b1_s4", en: "Chemistry", ur: "کیمسٹری (کیمیا)" },
      { id: "b1_s5", en: "Agriculture", ur: "زراعت" },
    ]
  },
  {
    boxNumber: 2,
    clusterTitleEn: "Architecture & Construction",
    clusterTitleUr: "فن تعمیر اور تعمیرات",
    colorScheme: "from-orange-600 to-amber-700",
    descriptionEn: "Careers in designing, planning, managing, building, and maintaining the built environment.",
    descriptionUr: "عمارتوں، شاہراہوں اور انفراسٹرکچر کے ڈیزائن، منصوبہ بندی اور تعمیر سے متعلق شعبہ۔",
    careerExamplesEn: ["Architect", "Civil Engineer", "Construction Manager", "Electrician", "Interior Designer"],
    careerExamplesUr: ["ماہرِ تعمیرات (آرکیٹیکٹ)", "سول انجینئر", "کنسٹرکشن مینیجر", "الیکٹریشن", "انٹیریئر ڈیزائنر"],
    activities: [
      { id: "b2_a1", en: "Read and follow blueprints and/or instructions.", ur: "نقشے اور ہدایات پڑھنا اور ان پر عمل کرنا۔" },
      { id: "b2_a2", en: "Picture in my mind what a finished product looks like.", ur: "ذہن میں تصور کرنا کہ تیار چیز کیسی نظر آئے گی۔" },
      { id: "b2_a3", en: "Work with my hands.", ur: "اپنے ہاتھوں سے کام کرنا۔" },
      { id: "b2_a4", en: "Perform work that requires precise results.", ur: "ایسا کام کرنا جس میں بالکل درست نتیجہ چاہیے ہو۔" },
      { id: "b2_a5", en: "Solve technical problems.", ur: "تکنیکی مسائل حل کرنا۔" },
      { id: "b2_a6", en: "Visit and learn from beautiful, historic, or interesting buildings.", ur: "خوبصورت، تاریخی یا دلچسپ عمارتیں دیکھنا اور ان سے سیکھنا۔" },
      { id: "b2_a7", en: "Follow logical, step-by-step procedures.", ur: "منطقی طریقے سے قدم بہ قدم کام کرنا۔" },
    ],
    personalQualities: [
      { id: "b2_q1", en: "Curious", ur: "تجسس (جاننے کا شوق)" },
      { id: "b2_q2", en: "Good at following directions", ur: "ہدایات پر اچھی طرح عمل کرنے والا" },
      { id: "b2_q3", en: "Pay attention to detail", ur: "چھوٹی چھوٹی باتوں پر دھیان دینا" },
      { id: "b2_q4", en: "Good at visualizing possibilities", ur: "امکانات کا تصور کرنے میں اچھا" },
      { id: "b2_q5", en: "Patient and persistent", ur: "صبر اور ثابت قدمی رکھنے والا" },
    ],
    schoolSubjects: [
      { id: "b2_s1", en: "Math", ur: "ریاضی" },
      { id: "b2_s2", en: "Drafting", ur: "ڈرافٹنگ (نقشہ بنانا)" },
      { id: "b2_s3", en: "Physical Sciences", ur: "طبیعی علوم (فزکس، کیمسٹری)" },
      { id: "b2_s4", en: "Construction Trades", ur: "تعمیراتی ہنر (جیسے معماری، لکڑی کا کام)" },
      { id: "b2_s5", en: "Electrical Trades/HVAC/Tech", ur: "بجلی، ایئر کنڈیشننگ / ٹیکنالوجی ایجوکیشن" },
    ]
  },
  {
    boxNumber: 3,
    clusterTitleEn: "Arts, A/V Technology & Communications",
    clusterTitleUr: "فنون، آڈیو ویڈیو ٹیکنالوجی اور ابلاغ",
    colorScheme: "from-pink-600 to-purple-700",
    descriptionEn: "Designing, producing, exhibiting, performing, writing, and publishing multimedia content including visual and performing arts.",
    descriptionUr: "میڈیا، فلم، تھیٹر، اینیمیشن، صحافت اور گرافک ڈیزائننگ کا وسیع شعبہ۔",
    careerExamplesEn: ["Graphic Designer", "Video Producer", "Journalist", "Animator", "Sound Engineer"],
    careerExamplesUr: ["گرافک ڈیزائنر", "ویڈیو پروڈیوسر", "صحافی / اینکر", "اینیمیٹر", "ساؤنڈ انجینئر"],
    activities: [
      { id: "b3_a1", en: "Use my imagination to communicate new information to others.", ur: "اپنے تخیل سے دوسروں تک نئی معلومات پہنچانا۔" },
      { id: "b3_a2", en: "Perform in front of others.", ur: "دوسروں کے سامنے پرفارم کرنا۔" },
      { id: "b3_a3", en: "Read and write.", ur: "پڑھنا اور لکھنا۔" },
      { id: "b3_a4", en: "Play a musical instrument.", ur: "کوئی ساز بجانا۔" },
      { id: "b3_a5", en: "Perform creative, artistic activities.", ur: "تخلیقی اور فنی سرگرمیاں کرنا۔" },
      { id: "b3_a6", en: "Use video and recording technology.", ur: "ویڈیو اور ریکارڈنگ ٹیکنالوجی استعمال کرنا۔" },
      { id: "b3_a7", en: "Design brochures and posters.", ur: "بروشر اور پوسٹر ڈیزائن کرنا۔" },
    ],
    personalQualities: [
      { id: "b3_q1", en: "Creative and imaginative", ur: "تخلیقی اور تصوراتی ذہن" },
      { id: "b3_q2", en: "Good communicator / good vocabulary", ur: "بات چیت میں اچھا، الفاظ کا اچھا ذخیرہ" },
      { id: "b3_q3", en: "Curious about new technology", ur: "نئی ٹیکنالوجی جاننے کا شوق" },
      { id: "b3_q4", en: "Relate well to feelings and thoughts of others", ur: "دوسروں کے جذبات اور سوچ کو اچھی طرح سمجھنا" },
      { id: "b3_q5", en: "Determined / tenacious", ur: "پختہ ارادہ اور ڈٹے رہنا" },
    ],
    schoolSubjects: [
      { id: "b3_s1", en: "Art / Graphic design", ur: "آرٹ / گرافک ڈیزائن" },
      { id: "b3_s2", en: "Music", ur: "موسیقی" },
      { id: "b3_s3", en: "Speech and Drama", ur: "تقریر اور ڈرامہ" },
      { id: "b3_s4", en: "Journalism / Literature", ur: "صحافت / ادب" },
      { id: "b3_s5", en: "Audiovisual Technologies", ur: "آڈیو ویژول ٹیکنالوجی" },
    ]
  },
  {
    boxNumber: 4,
    clusterTitleEn: "Business Management & Administration",
    clusterTitleUr: "کاروباری انتظام اور نظم و نسق",
    colorScheme: "from-blue-600 to-cyan-700",
    descriptionEn: "Planning, organizing, directing and evaluating business functions essential to efficient and productive business operations.",
    descriptionUr: "کسی بھی ادارے یا کمپنی کو منظم انداز میں چلانے، منصوبہ بندی اور قیادت کا شعبہ۔",
    careerExamplesEn: ["Business Executive", "Human Resources Manager", "Operations Analyst", "Project Manager", "Office Administrator"],
    careerExamplesUr: ["بزنس ایگزیکٹو", "ایچ آر منیجر", "آپریشنز تجزیہ کار", "پروجیکٹ منیجر", "دفتر منتظم"],
    activities: [
      { id: "b4_a1", en: "Perform routine, organized activities but can be flexible.", ur: "روزمردہ کے منظم کام کرنا، لیکن ضرورت پر لچک بھی دکھانا۔" },
      { id: "b4_a2", en: "Work with numbers and detailed information.", ur: "اعداد اور تفصیلی معلومات کے ساتھ کام کرنا۔" },
      { id: "b4_a3", en: "Be the leader in a group.", ur: "گروپ کا لیڈر بننا۔" },
      { id: "b4_a4", en: "Make business contact with people.", ur: "کاروباری سلسلے میں لوگوں سے رابطہ کرنا۔" },
      { id: "b4_a5", en: "Work with computer programs.", ur: "کمپیوٹر پروگراموں پر کام کرنا۔" },
      { id: "b4_a6", en: "Create reports and communicate ideas.", ur: "رپورٹیں بنانا اور اپنے خیالات پیش کرنا۔" },
      { id: "b4_a7", en: "Plan my work and follow instructions without close supervision.", ur: "اپنے کام کی منصوبہ بندی کرنا اور بغیر نگرانی کے ہدایات پر عمل کرنا۔" },
    ],
    personalQualities: [
      { id: "b4_q1", en: "Organized", ur: "منظم" },
      { id: "b4_q2", en: "Practical and logical", ur: "عملی اور منطقی" },
      { id: "b4_q3", en: "Patient", ur: "صابر اور پرسکون" },
      { id: "b4_q4", en: "Tactful", ur: "سمجھداری اور تدبر سے بات کرنا" },
      { id: "b4_q5", en: "Responsible", ur: "ذمہ داری کا احساس" },
    ],
    schoolSubjects: [
      { id: "b4_s1", en: "Computer Applications / IT", ur: "کمپیوٹر ایپلی کیشنز / بزنس آئی ٹی" },
      { id: "b4_s2", en: "Accounting", ur: "اکاؤنٹنگ (حساب کتاب)" },
      { id: "b4_s3", en: "Math", ur: "ریاضی" },
      { id: "b4_s4", en: "English", ur: "انگریزی زبان" },
      { id: "b4_s5", en: "Economics", ur: "معاشیات (اکنامکس)" },
    ]
  },
  {
    boxNumber: 5,
    clusterTitleEn: "Education & Training",
    clusterTitleUr: "تعلیم و تربیت",
    colorScheme: "from-teal-600 to-emerald-700",
    descriptionEn: "Planning, managing and providing education and training services, and related learning support services.",
    descriptionUr: "اسکول، کالج، یونیورسٹیوں اور تربیتی اداروں میں تعلیم اور رہنمائی کا شعبہ۔",
    careerExamplesEn: ["Teacher / Professor", "School Principal", "Corporate Trainer", "Educational Counselor", "Curriculum Developer"],
    careerExamplesUr: ["استاد / پروفیسر", "پرنسپل", "تربیت کار (ٹرینر)", "تعلیمی کونسلر", "نصاب ساز"],
    activities: [
      { id: "b5_a1", en: "Communicate with different types of people.", ur: "مختلف قسم کے لوگوں سے بات چیت کرنا۔" },
      { id: "b5_a2", en: "Help others with their homework or to learn new things.", ur: "دوسروں کو ہوم ورک میں مدد دینا یا نئی چیزیں سکھانا۔" },
      { id: "b5_a3", en: "Go to school.", ur: "اسکول جانا اور نیا سیکھنا۔" },
      { id: "b5_a4", en: "Direct and plan activities for others.", ur: "دوسروں کے لیے سرگرمیاں بنانا اور ان کی رہنمائی کرنا۔" },
      { id: "b5_a5", en: "Handle several responsibilities at once.", ur: "ایک ساتھ کئی ذمہ داریاں سنبھالنا۔" },
      { id: "b5_a6", en: "Acquire new information.", ur: "نئی معلومات حاصل کرنا۔" },
      { id: "b5_a7", en: "Help people overcome their challenges.", ur: "لوگوں کو ان کی مشکلات سے نکلنے میں مدد دینا۔" },
    ],
    personalQualities: [
      { id: "b5_q1", en: "Friendly", ur: "دوستانہ مزاج" },
      { id: "b5_q2", en: "Decision maker", ur: "فیصلہ کرنے کی صلاحیت" },
      { id: "b5_q3", en: "Helpful", ur: "مددگار اور ہمدرد" },
      { id: "b5_q4", en: "Innovative / Inquisitive", ur: "نئے خیالات سوچنا اور سوال کرنا" },
      { id: "b5_q5", en: "Good listener", ur: "توجہ سے سننے والا" },
    ],
    schoolSubjects: [
      { id: "b5_s1", en: "Language Arts (Urdu / English)", ur: "زبان و ادب (اردو / انگریزی)" },
      { id: "b5_s2", en: "Social Studies", ur: "معاشرتی علوم" },
      { id: "b5_s3", en: "Math", ur: "ریاضی" },
      { id: "b5_s4", en: "Science", ur: "سائنس" },
      { id: "b5_s5", en: "Psychology", ur: "نفسیات" },
    ]
  },
  {
    boxNumber: 6,
    clusterTitleEn: "Finance",
    clusterTitleUr: "مالیات (فنانس)",
    colorScheme: "from-emerald-600 to-green-700",
    descriptionEn: "Planning, services for financial and investment planning, banking, insurance, and business financial management.",
    descriptionUr: "بینکنگ، مالیاتی سرمایہ کاری، انشورنس اور معاشی پالیسیوں کا اہم شعبہ۔",
    careerExamplesEn: ["Financial Analyst", "Chartered Accountant (CA)", "Bank Manager", "Actuary", "Stock Broker"],
    careerExamplesUr: ["مالیاتی تجزیہ کار", "چارٹرڈ اکاؤنٹنٹ", "بینک مینیجر", "ایکچوری", "اسٹاک بروکر"],
    activities: [
      { id: "b6_a1", en: "Work with numbers.", ur: "اعداد کے ساتھ کام کرنا۔" },
      { id: "b6_a2", en: "Work to meet a deadline.", ur: "مقررہ وقت تک کام مکمل کرنا۔" },
      { id: "b6_a3", en: "Make predictions based on existing facts.", ur: "موجودہ حقائق کی بنیاد پر اندازے لگانا۔" },
      { id: "b6_a4", en: "Have a framework of rules by which to operate.", ur: "پہلے سے طے شدہ اصولوں اور ضابطوں کے تحت کام کرنا۔" },
      { id: "b6_a5", en: "Analyze financial information and interpret it to others.", ur: "مالی معلومات کا جائزہ لینا اور دوسروں کو سمجھانا۔" },
      { id: "b6_a6", en: "Handle money with accuracy and reliability.", ur: "پیسوں کا حساب درستی اور ایمانداری سے رکھنا۔" },
      { id: "b6_a7", en: "Take pride in the way I dress and look.", ur: "اپنے لباس اور حلیے کا خیال رکھنا اور اس پر فخر کرنا۔" },
    ],
    personalQualities: [
      { id: "b6_q1", en: "Trustworthy", ur: "قابل اعتماد اور دیانتدار" },
      { id: "b6_q2", en: "Orderly", ur: "سلیقہ مند اور منظم" },
      { id: "b6_q3", en: "Self-confident", ur: "خود اعتمادی" },
      { id: "b6_q4", en: "Logical", ur: "منطقی سوچ" },
      { id: "b6_q5", en: "Methodical or efficient", ur: "طریقے سے اور مؤثر انداز میں کام کرنا" },
    ],
    schoolSubjects: [
      { id: "b6_s1", en: "Accounting", ur: "اکاؤنٹنگ (حساب کتاب)" },
      { id: "b6_s2", en: "Math", ur: "ریاضی" },
      { id: "b6_s3", en: "Economics", ur: "معاشیات (اکنامکس)" },
      { id: "b6_s4", en: "Banking / Financial Services", ur: "بینکنگ / مالی خدمات" },
      { id: "b6_s5", en: "Business Law", ur: "کاروباری قانون" },
    ]
  },
  {
    boxNumber: 7,
    clusterTitleEn: "Government & Public Administration",
    clusterTitleUr: "حکومت اور عوامی انتظامیہ",
    colorScheme: "from-indigo-600 to-slate-800",
    descriptionEn: "Planning and executing government functions at local, state and federal levels, including national security and foreign service.",
    descriptionUr: "سرکاری اداروں، امور خارجہ، پالیسی سازی اور عوامی فلاح کے حکومتی شعبے۔",
    careerExamplesEn: ["Civil Servant (CSS)", "Diplomat", "Policy Analyst", "Urban Planner", "Public Administrator"],
    careerExamplesUr: ["سی ایس ایس افسر / بیوروکریٹ", "سفارت کار", "پالیسی تجزیہ نگار", "شہری منصوبہ ساز", "پبلک ایڈمنسٹریٹر"],
    activities: [
      { id: "b7_a1", en: "Be involved in politics.", ur: "سیاست اور عوامی معاملات میں دلچسپی لینا۔" },
      { id: "b7_a2", en: "Negotiate, defend, and debate ideas and topics.", ur: "بات چیت سے معاملات طے کرنا، اپنی بات کا دفاع کرنا اور موضوعات پر بحث کرنا۔" },
      { id: "b7_a3", en: "Plan activities and work cooperatively with others.", ur: "سرگرمیوں کی منصوبہ بندی کرنا اور دوسروں کے ساتھ مل کر کام کرنا۔" },
      { id: "b7_a4", en: "Work with details.", ur: "تفصیلات کے ساتھ کام کرنا۔" },
      { id: "b7_a5", en: "Perform a variety of duties that may change often.", ur: "طرح طرح کے کام کرنا جو اکثر بدلتے رہیں۔" },
      { id: "b7_a6", en: "Analyze information and interpret it to others.", ur: "معلومات کا جائزہ لینا اور دوسروں کو سمجھانا۔" },
      { id: "b7_a7", en: "Travel and see things that are new to me.", ur: "سفر کرنا اور نئی چیزیں دیکھنا۔" },
    ],
    personalQualities: [
      { id: "b7_q1", en: "Good communicator", ur: "بات چیت میں اچھا" },
      { id: "b7_q2", en: "Competitive", ur: "مقابلے کا جذبہ" },
      { id: "b7_q3", en: "Service-minded", ur: "خدمت کا جذبہ" },
      { id: "b7_q4", en: "Well-organized", ur: "بہت منظم" },
      { id: "b7_q5", en: "Problem solver", ur: "مسائل حل کرنے والا" },
    ],
    schoolSubjects: [
      { id: "b7_s1", en: "Government (Civics)", ur: "حکومت اور نظامِ حکومت (شہریت)" },
      { id: "b7_s2", en: "Language Arts", ur: "زبان و ادب (اردو / انگریزی)" },
      { id: "b7_s3", en: "History", ur: "تاریخ" },
      { id: "b7_s4", en: "Math", ur: "ریاضی" },
      { id: "b7_s5", en: "Foreign Language", ur: "غیر ملکی زبان (جیسے عربی، چینی، فرانسیسی)" },
    ]
  },
  {
    boxNumber: 8,
    clusterTitleEn: "Health Science",
    clusterTitleUr: "صحت اور طبی سائنس",
    colorScheme: "from-red-600 to-rose-700",
    descriptionEn: "Planning, managing, and providing therapeutic services, diagnostic services, health informatics, and biotechnology research.",
    descriptionUr: "علاج معالجہ، ڈاکٹرز، نرسنگ، ادویات اور طبی تحقیق کا شعبہ۔",
    careerExamplesEn: ["Doctor / Physician", "Surgeon", "Nurse", "Pharmacist", "Medical Lab Scientist"],
    careerExamplesUr: ["ڈاکٹر", "سرجن", "نرس", "فارماسسٹ", "میڈیکل لیب سائنسدان"],
    activities: [
      { id: "b8_a1", en: "Work under pressure.", ur: "دباؤ میں کام کرنا۔" },
      { id: "b8_a2", en: "Help sick people and animals.", ur: "بیمار لوگوں اور جانوروں کی مدد کرنا۔" },
      { id: "b8_a3", en: "Make decisions based on logic and information.", ur: "منطق اور معلومات کی بنیاد پر فیصلے کرنا۔" },
      { id: "b8_a4", en: "Participate in health and science classes.", ur: "صحت اور سائنس کی کلاسوں میں حصہ لینا۔" },
      { id: "b8_a5", en: "Respond quickly and calmly in emergencies.", ur: "ہنگامی حالات میں جلدی اور پرسکون رہ کر قدم اٹھانا۔" },
      { id: "b8_a6", en: "Work as a member of a team.", ur: "ٹیم کے رکن کے طور پر کام کرنا۔" },
      { id: "b8_a7", en: "Follow guidelines precisely and meet strict standards of accuracy.", ur: "ہدایات پر بالکل درست عمل کرنا اور سخت معیار پر پورا اترنا۔" },
    ],
    personalQualities: [
      { id: "b8_q1", en: "Compassionate and caring", ur: "ہمدردی اور خیال رکھنا" },
      { id: "b8_q2", en: "Good at following directions", ur: "ہدایات پر اچھی طرح عمل کرنا" },
      { id: "b8_q3", en: "Conscientious and careful", ur: "ذمہ دار اور محتاط" },
      { id: "b8_q4", en: "Patient", ur: "صبر و تحمل" },
      { id: "b8_q5", en: "Good listener", ur: "توجہ سے سننا" },
    ],
    schoolSubjects: [
      { id: "b8_s1", en: "Biological Sciences", ur: "حیاتیات (بائیولوجی)" },
      { id: "b8_s2", en: "Chemistry", ur: "کیمیا (کیمسٹری)" },
      { id: "b8_s3", en: "Math", ur: "ریاضی" },
      { id: "b8_s4", en: "Occupational Health classes", ur: "پیشہ ورانہ صحت کی کلاسیں" },
      { id: "b8_s5", en: "Language Arts", ur: "زبان و ادب (اردو / انگریزی)" },
    ]
  },
  {
    boxNumber: 9,
    clusterTitleEn: "Hospitality & Tourism",
    clusterTitleUr: "مہمان نوازی اور سیاحت",
    colorScheme: "from-amber-500 to-orange-600",
    descriptionEn: "Management, marketing and operations of restaurants and other food services, lodging, attractions, recreation events and travel.",
    descriptionUr: "ہوٹل مینجمنٹ، سیاحت، ایونٹ مینجمنٹ اور فوڈ سروسز کا پرکشش شعبہ۔",
    careerExamplesEn: ["Hotel General Manager", "Executive Chef", "Tour Director", "Event Planner", "Travel Consultant"],
    careerExamplesUr: ["ہوٹل جنرل منیجر", "ایگزیکٹو شیف", "ٹور گائیڈ / ڈائریکٹر", "ایونٹ مینیجر", "ٹریول کنسلٹنٹ"],
    activities: [
      { id: "b9_a1", en: "Investigate new places and activities.", ur: "نئی جگہوں اور نئی سرگرمیوں کو کھوجنا۔" },
      { id: "b9_a2", en: "Work with all ages and types of people.", ur: "ہر عمر اور ہر طرح کے لوگوں کے ساتھ کام کرنا۔" },
      { id: "b9_a3", en: "Organize activities in which other people enjoy themselves.", ur: "ایسی سرگرمیاں کروانا جن میں دوسروں کو مزہ آئے۔" },
      { id: "b9_a4", en: "Have a flexible schedule.", ur: "لچکدار اوقاتِ کار رکھنا۔" },
      { id: "b9_a5", en: "Help people make up their minds.", ur: "لوگوں کو فیصلہ کرنے میں مدد دینا۔" },
      { id: "b9_a6", en: "Communicate easily, tactfully, and courteously.", ur: "آسانی، سمجھداری اور شائستگی سے بات کرنا۔" },
      { id: "b9_a7", en: "Learn about other cultures.", ur: "دوسری ثقافتوں کے بارے میں جاننا۔" },
    ],
    personalQualities: [
      { id: "b9_q1", en: "Tactful", ur: "نرمی اور سمجھداری سے بات کرنا" },
      { id: "b9_q2", en: "Self-motivated", ur: "خود سے کام کرنے کا حوصلہ" },
      { id: "b9_q3", en: "Works well with others", ur: "دوسروں کے ساتھ اچھی طرح کام کرنا" },
      { id: "b9_q4", en: "Outgoing", ur: "ملنسار اور پرجوش" },
      { id: "b9_q5", en: "Slow to anger", ur: "دیر سے غصہ آنا اور پرسکون رہنا" },
    ],
    schoolSubjects: [
      { id: "b9_s1", en: "Language Arts / Speech", ur: "زبان و ادب / تقریر" },
      { id: "b9_s2", en: "Foreign Language", ur: "غیر ملکی زبان (عربی، فرانسیسی، چینی)" },
      { id: "b9_s3", en: "Social Sciences", ur: "سماجی علوم" },
      { id: "b9_s4", en: "Marketing", ur: "مارکیٹنگ" },
      { id: "b9_s5", en: "Food Services", ur: "فوڈ سروسز (کھانے پینے کا کاروبار)" },
    ]
  },
  {
    boxNumber: 10,
    clusterTitleEn: "Human Services",
    clusterTitleUr: "انسانی خدمات (سماجی خدمت)",
    colorScheme: "from-purple-600 to-violet-800",
    descriptionEn: "Preparing individuals for employment in career pathways that relate to families and human needs such as counseling, personal care and community support.",
    descriptionUr: "لوگوں کی نفسیاتی اور سماجی مدد، خاندانی بہبود، کونسلنگ اور معاشرتی ترقی کا میدان۔",
    careerExamplesEn: ["Clinical Psychologist", "Social Worker", "Child Care Director", "Rehabilitation Specialist", "Community Organizer"],
    careerExamplesUr: ["ماہرِ نفسیات", "سوشل ورکر", "چائلڈ کیئر ڈائریکٹر", "بحالی کا ماہر", "کمیونٹی آرگنائزر"],
    activities: [
      { id: "b10_a1", en: "Care about people, their needs, and their problems.", ur: "لوگوں، ان کی ضرورتوں اور مسائل کی فکر کرنا۔" },
      { id: "b10_a2", en: "Participate in community services and/or volunteering.", ur: "کمیونٹی کی خدمت یا رضاکارانہ کام میں حصہ لینا۔" },
      { id: "b10_a3", en: "Listen to other people's viewpoints.", ur: "دوسروں کی رائے غور سے سننا۔" },
      { id: "b10_a4", en: "Help people be at their best.", ur: "لوگوں کو اپنا بہترین بننے میں مدد دینا۔" },
      { id: "b10_a5", en: "Work with people from preschool age to old age.", ur: "چھوٹے بچوں سے لے کر بزرگوں تک، ہر عمر کے لوگوں کے ساتھ کام کرنا۔" },
      { id: "b10_a6", en: "Think of new ways to do things.", ur: "کام کرنے کے نئے طریقے سوچنا۔" },
      { id: "b10_a7", en: "Make friends with different kinds of people.", ur: "مختلف قسم کے لوگوں سے دوستی کرنا۔" },
    ],
    personalQualities: [
      { id: "b10_q1", en: "Good communicator / good listener", ur: "بات کرنے اور سننے میں اچھا" },
      { id: "b10_q2", en: "Caring", ur: "خیال رکھنے والا" },
      { id: "b10_q3", en: "Non-materialistic", ur: "مال و دولت کا لالچ نہ ہونا" },
      { id: "b10_q4", en: "Intuitive and logical", ur: "اندازہ لگانے اور منطق سے سوچنے کی صلاحیت" },
      { id: "b10_q5", en: "Non-judgmental", ur: "دوسروں کے بارے میں جلد رائے قائم نہ کرنا" },
    ],
    schoolSubjects: [
      { id: "b10_s1", en: "Language Arts", ur: "زبان و ادب (اردو / انگریزی)" },
      { id: "b10_s2", en: "Psychology / Sociology", ur: "نفسیات / سماجیات" },
      { id: "b10_s3", en: "Family & Consumer Sciences", ur: "خاندانی اور صارفی علوم (ہوم اکنامکس)" },
      { id: "b10_s4", en: "Finance", ur: "مالیات" },
      { id: "b10_s5", en: "Foreign Language", ur: "غیر ملکی زبان" },
    ]
  },
  {
    boxNumber: 11,
    clusterTitleEn: "Information Technology",
    clusterTitleUr: "انفارمیشن ٹیکنالوجی (آئی ٹی)",
    colorScheme: "from-sky-600 to-blue-800",
    descriptionEn: "Design, development, support and management of hardware, software, multimedia and systems integration services.",
    descriptionUr: "سافٹ ویئر ڈویلپمنٹ، کمپیوٹر نیٹ ورکنگ، ڈیٹا سائنس اور آرٹیفیشل انٹیلیجنس۔",
    careerExamplesEn: ["Software Engineer", "Cybersecurity Specialist", "Data Scientist", "Cloud Architect", "Network Engineer"],
    careerExamplesUr: ["سافٹ ویئر انجینئر", "سائبر سیکیورٹی ماہر", "ڈیٹا سائنسدان", "کلاؤڈ آرکیٹیکٹ", "نیٹ ورک انجینئر"],
    activities: [
      { id: "b11_a1", en: "Work with computers.", ur: "کمپیوٹر پر کام کرنا۔" },
      { id: "b11_a2", en: "Reason clearly and logically to solve complex problems.", ur: "مشکل مسائل حل کرنے کے لیے صاف اور منطقی انداز میں سوچنا۔" },
      { id: "b11_a3", en: "Use machines, techniques, and processes.", ur: "مشینیں، تکنیکیں اور طریقے استعمال کرنا۔" },
      { id: "b11_a4", en: "Read technical materials and diagrams and solve technical problems.", ur: "تکنیکی مواد اور خاکے پڑھنا اور تکنیکی مسائل حل کرنا۔" },
      { id: "b11_a5", en: "Adapt to change.", ur: "تبدیلی کے ساتھ خود کو ڈھالنا۔" },
      { id: "b11_a6", en: "Play video games and figure out how they work.", ur: "ویڈیو گیمز کھیلنا اور سمجھنا کہ وہ کیسے کام کرتی ہیں۔" },
      { id: "b11_a7", en: "Concentrate for long periods without being distracted.", ur: "بغیر بھٹکے دیر تک توجہ سے کام کرنا۔" },
    ],
    personalQualities: [
      { id: "b11_q1", en: "Logical / analytical thinker", ur: "منطقی اور تجزیاتی سوچ" },
      { id: "b11_q2", en: "See details in the big picture", ur: "پورے منظر کے ساتھ چھوٹی باتیں بھی دیکھ لینا" },
      { id: "b11_q3", en: "Persistent", ur: "ثابت قدمی اور مستقل مزاجی" },
      { id: "b11_q4", en: "Good concentration skills", ur: "توجہ جمانے میں اچھا" },
      { id: "b11_q5", en: "Precise and accurate", ur: "درست اور باریک بین" },
    ],
    schoolSubjects: [
      { id: "b11_s1", en: "Math", ur: "ریاضی" },
      { id: "b11_s2", en: "Science", ur: "سائنس" },
      { id: "b11_s3", en: "Computer Tech / Applications", ur: "کمپیوٹر ٹیکنالوجی / ایپلی کیشنز" },
      { id: "b11_s4", en: "Communications", ur: "ابلاغیات (کمیونیکیشن)" },
      { id: "b11_s5", en: "Graphic Design", ur: "گرافک ڈیزائن" },
    ]
  },
  {
    boxNumber: 12,
    clusterTitleEn: "Law, Public Safety, Corrections & Security",
    clusterTitleUr: "قانون، عوامی تحفظ، اصلاح جرائم اور سیکیورٹی",
    colorScheme: "from-blue-700 to-indigo-950",
    descriptionEn: "Planning, managing, and providing legal, public safety, protective services and homeland security, including professional and technical support services.",
    descriptionUr: "قانون دان، ججز، پولیس، عدالتی نظام اور سلامتی کے ادارے",
    careerExamplesEn: ["Lawyer / Attorney", "Police Officer / Investigator", "Judge", "Forensic Expert", "Cyber Defense Analyst"],
    careerExamplesUr: ["وکیل / ایڈووکیٹ", "پولیس آفیسر / تفتیش کار", "جج", "فارنزک ماہر", "سیکیورٹی افسر"],
    activities: [
      { id: "b12_a1", en: "Work under pressure or in the face of danger.", ur: "دباؤ میں یا خطرے کے سامنے کام کرنا۔" },
      { id: "b12_a2", en: "Make decisions based on my own observations.", ur: "اپنے مشاہدے کی بنیاد پر فیصلے کرنا۔" },
      { id: "b12_a3", en: "Interact with other people.", ur: "دوسرے لوگوں سے میل جول رکھنا۔" },
      { id: "b12_a4", en: "Be in positions of authority.", ur: "ذمہ داری اور اختیار والے عہدے پر ہونا۔" },
      { id: "b12_a5", en: "Respect rules and regulations.", ur: "قواعد و ضوابط کا احترام کرنا۔" },
      { id: "b12_a6", en: "Debate and win arguments.", ur: "بحث کرنا اور دلیل سے اپنی بات منوانا۔" },
      { id: "b12_a7", en: "Observe and analyze people's behavior.", ur: "لوگوں کے رویوں کو دیکھنا اور سمجھنا۔" },
    ],
    personalQualities: [
      { id: "b12_q1", en: "Adventurous", ur: "مہم جو" },
      { id: "b12_q2", en: "Dependable", ur: "قابل بھروسا" },
      { id: "b12_q3", en: "Community-minded", ur: "معاشرے کی بھلائی کا جذبہ" },
      { id: "b12_q4", en: "Decisive", ur: "پکا اور فوری فیصلہ کرنا" },
      { id: "b12_q5", en: "Optimistic", ur: "پرامید" },
    ],
    schoolSubjects: [
      { id: "b12_s1", en: "Language Arts", ur: "زبان و ادب (اردو / انگریزی)" },
      { id: "b12_s2", en: "Psychology / Sociology", ur: "نفسیات / سماجیات" },
      { id: "b12_s3", en: "Government / History", ur: "حکومت / تاریخ" },
      { id: "b12_s4", en: "Law Enforcement", ur: "قانون نافذ کرنے والے ادارے (جیسے پولیس)" },
      { id: "b12_s5", en: "First Aid / First Responder", ur: "ابتدائی طبی امداد / ہنگامی امداد" },
    ]
  },
  {
    boxNumber: 13,
    clusterTitleEn: "Manufacturing",
    clusterTitleUr: "صنعتی پیداوار (مینوفیکچرنگ)",
    colorScheme: "from-stone-600 to-amber-800",
    descriptionEn: "Planning, managing and performing the processing of materials into intermediate or final products and related professional and technical support activities.",
    descriptionUr: "فیکٹریوں، پلانٹس، مشینی پرزوں اور مصنوعات کی بڑے پیمانے پر تیاری اور آپریشنز۔",
    careerExamplesEn: ["Manufacturing Engineer", "Quality Control Inspector", "Robotics Technician", "Plant Manager", "Industrial Designer"],
    careerExamplesUr: ["مینوفیکچرنگ انجینئر", "کوالٹی کنٹرول انسپکٹر", "روبوٹکس ٹیکنیشن", "پلانٹ مینیجر", "صنعتی ڈیزائنر"],
    activities: [
      { id: "b13_a1", en: "Work with my hands and learn that way.", ur: "ہاتھوں سے کام کر کے سیکھنا۔" },
      { id: "b13_a2", en: "Put things together.", ur: "چیزیں جوڑنا اور بنانا۔" },
      { id: "b13_a3", en: "Do routine, organized and accurate work.", ur: "روزمردہ کا منظم اور درست کام کرنا۔" },
      { id: "b13_a4", en: "Perform activities that produce tangible results.", ur: "ایسے کام کرنا جن کا نتیجہ آنکھوں کے سامنے نظر آئے۔" },
      { id: "b13_a5", en: "Apply math to work out solutions.", ur: "حل نکالنے کے لیے ریاضی استعمال کرنا۔" },
      { id: "b13_a6", en: "Use hand and power tools and operate equipment/machinery.", ur: "ہاتھ کے اوزار اور بجلی سے چلنے والے اوزار استعمال کرنا اور مشینری چلانا۔" },
      { id: "b13_a7", en: "Visualize objects in three dimensions from flat drawings.", ur: "سادہ نقشے دیکھ کر چیز کو تین اطراف (3D) میں تصور کرنا۔" },
    ],
    personalQualities: [
      { id: "b13_q1", en: "Practical", ur: "عملی انسان" },
      { id: "b13_q2", en: "Observant", ur: "غور سے مشاہدہ کرنا" },
      { id: "b13_q3", en: "Physically active", ur: "چاق و چوبند" },
      { id: "b13_q4", en: "Step-by-step thinker", ur: "قدم بہ قدم سوچنا" },
      { id: "b13_q5", en: "Coordinated", ur: "ہاتھ اور آنکھ کا اچھا تال میل" },
    ],
    schoolSubjects: [
      { id: "b13_s1", en: "Math-Geometry", ur: "ریاضی (جیومیٹری)" },
      { id: "b13_s2", en: "Chemistry", ur: "کیمیا (کیمسٹری)" },
      { id: "b13_s3", en: "Trade and Industry courses", ur: "ہنر اور صنعت کے کورسز (ووکیشنل)" },
      { id: "b13_s4", en: "Physics", ur: "طبیعیات (فزکس)" },
      { id: "b13_s5", en: "Language Arts", ur: "زبان و ادب" },
    ]
  },
  {
    boxNumber: 14,
    clusterTitleEn: "Marketing",
    clusterTitleUr: "مارکیٹنگ اور سیلز",
    colorScheme: "from-rose-600 to-red-800",
    descriptionEn: "Planning, managing, and performing marketing activities to reach organizational objectives such as brand management, advertising and sales.",
    descriptionUr: "مصنوعات کی تشہیر، برانڈنگ، پبلک ریلیشنز اور فروخت میں مہارت۔",
    careerExamplesEn: ["Marketing Director", "Brand Strategist", "Market Research Analyst", "Digital Marketer", "Public Relations Specialist"],
    careerExamplesUr: ["مارکیٹنگ ڈائریکٹر", "برانڈ اسٹریٹیجسٹ", "مارکیٹ ریسرچ اینالسٹ", "ڈیجیٹل مارکیٹر", "پی آر آفیسر"],
    activities: [
      { id: "b14_a1", en: "Shop and go to the mall.", ur: "خریداری کرنا اور بازار / مال جانا۔" },
      { id: "b14_a2", en: "Be in charge.", ur: "کام کی ذمہ داری خود سنبھالنا۔" },
      { id: "b14_a3", en: "Make displays and promote ideas.", ur: "نمائش (ڈسپلے) سجانا اور اپنے خیالات کی تشہیر کرنا۔" },
      { id: "b14_a4", en: "Give presentations and enjoy public speaking.", ur: "پریزینٹیشن دینا اور لوگوں کے سامنے بولنا پسند کرنا۔" },
      { id: "b14_a5", en: "Persuade people to buy products or to participate in activities.", ur: "لوگوں کو چیزیں خریدنے یا سرگرمیوں میں حصہ لینے پر راضی کرنا۔" },
      { id: "b14_a6", en: "Communicate my ideas to other people.", ur: "اپنے خیالات دوسروں تک پہنچانا۔" },
      { id: "b14_a7", en: "Take advantage of opportunities to make extra money.", ur: "اضافی پیسے کمانے کے مواقع سے فائدہ اٹھانا۔" },
    ],
    personalQualities: [
      { id: "b14_q1", en: "Enthusiastic", ur: "پُرجوش" },
      { id: "b14_q2", en: "Competitive", ur: "مقابلے کا جذبہ" },
      { id: "b14_q3", en: "Creative", ur: "تخلیقی" },
      { id: "b14_q4", en: "Self-motivated", ur: "خود سے کام کرنے کا حوصلہ" },
      { id: "b14_q5", en: "Persuasive", ur: "دوسروں کو قائل کر لینا" },
    ],
    schoolSubjects: [
      { id: "b14_s1", en: "Language Arts", ur: "زبان و ادب (اردو / انگریزی)" },
      { id: "b14_s2", en: "Math", ur: "ریاضی" },
      { id: "b14_s3", en: "Business Education / Marketing", ur: "کاروباری تعلیم / مارکیٹنگ" },
      { id: "b14_s4", en: "Economics", ur: "معاشیات" },
      { id: "b14_s5", en: "Computer Applications", ur: "کمپیوٹر ایپلی کیشنز" },
    ]
  },
  {
    boxNumber: 15,
    clusterTitleEn: "Science, Technology, Engineering & Mathematics (STEM)",
    clusterTitleUr: "سائنس، ٹیکنالوجی، انجینئرنگ اور ریاضی",
    colorScheme: "from-blue-600 to-indigo-800",
    descriptionEn: "Planning, managing, and providing scientific research and professional and technical services including laboratory and testing services, and research and development services.",
    descriptionUr: "سائنسی تحقیق، جدید ایجادات، خلائی علوم اور جدید انجینئرنگ۔",
    careerExamplesEn: ["Mechanical Engineer", "Biomedical Scientist", "Robotics Engineer", "Astrophysicist", "Data Researcher"],
    careerExamplesUr: ["مکینیکل انجینئر", "بائیو میڈیکل سائنسدان", "روبوٹکس انجینئر", "خلائی سائنسدان", "سائنسی محقق"],
    activities: [
      { id: "b15_a1", en: "Interpret formulas.", ur: "فارمولوں کو سمجھنا اور استعمال کرنا۔" },
      { id: "b15_a2", en: "Find the answers to questions.", ur: "سوالوں کے جواب ڈھونڈنا۔" },
      { id: "b15_a3", en: "Work in a laboratory.", ur: "لیبارٹری میں کام کرنا۔" },
      { id: "b15_a4", en: "Figure out how things work and investigate new things.", ur: "یہ جاننا کہ چیزیں کیسے کام کرتی ہیں اور نئی چیزوں کی تحقیق کرنا۔" },
      { id: "b15_a5", en: "Explore new technology.", ur: "نئی ٹیکنالوجی کو کھنگالنا (دریافت کرنا)۔" },
      { id: "b15_a6", en: "Experiment to find the best way to do something.", ur: "کسی کام کا بہترین طریقہ ڈھونڈنے کے لیے تجربے کرنا۔" },
      { id: "b15_a7", en: "Pay attention to details and help things be precise.", ur: "تفصیلات پر دھیان دینا اور کام کو درست بنانا۔" },
    ],
    personalQualities: [
      { id: "b15_q1", en: "Detail-oriented", ur: "تفصیل پر توجہ دینا" },
      { id: "b15_q2", en: "Inquisitive", ur: "سوال کرنا اور کھوج لگانا" },
      { id: "b15_q3", en: "Objective", ur: "غیر جانبدار، حقائق پر مبنی سوچ" },
      { id: "b15_q4", en: "Methodical", ur: "طریقے سے کام کرنا" },
      { id: "b15_q5", en: "Mechanically inclined", ur: "مشینوں کی سمجھ اور دلچسپی" },
    ],
    schoolSubjects: [
      { id: "b15_s1", en: "Math", ur: "ریاضی" },
      { id: "b15_s2", en: "Science", ur: "سائنس" },
      { id: "b15_s3", en: "Drafting / CAD", ur: "ڈرافٹنگ / کمپیوٹر کی مدد سے ڈرافٹنگ (CAD)" },
      { id: "b15_s4", en: "Electronics / Computer Networking", ur: "الیکٹرانکس / کمپیوٹر نیٹ ورکنگ" },
      { id: "b15_s5", en: "Technical Classes / Tech Education", ur: "تکنیکی کلاسیں / ٹیکنالوجی ایجوکیشن" },
    ]
  },
  {
    boxNumber: 16,
    clusterTitleEn: "Transportation, Distribution & Logistics",
    clusterTitleUr: "ٹرانسپورٹ، ترسیل اور لاجسٹکس",
    colorScheme: "from-amber-700 to-slate-800",
    descriptionEn: "Planning, management, and movement of people, materials, and goods by road, pipeline, air, rail and water and related professional support services.",
    descriptionUr: "سامان اور مسافروں کی ترسیل، ایوی ایشن، جہاز رانی، سپلائی چین اور لاجسٹکس کا عالمی نیٹ ورک۔",
    careerExamplesEn: ["Commercial Pilot", "Logistics Director", "Supply Chain Manager", "Automotive Engineer", "Air Traffic Controller"],
    careerExamplesUr: ["کمرشل پائلٹ", "لاجسٹکس ڈائریکٹر", "سپلائی چین منیجر", "آٹوموٹو انجینئر", "ایئر ٹریفک کنٹرولر"],
    activities: [
      { id: "b16_a1", en: "Travel.", ur: "سفر کرنا۔" },
      { id: "b16_a2", en: "See well and have quick reflexes.", ur: "نظر تیز ہونا اور فوری ردعمل دکھانا۔" },
      { id: "b16_a3", en: "Solve mechanical problems.", ur: "مشینی خرابیاں حل کرنا۔" },
      { id: "b16_a4", en: "Design efficient processes.", ur: "کام کے مؤثر طریقے بنانا۔" },
      { id: "b16_a5", en: "Anticipate needs and prepare to meet them.", ur: "ضرورتوں کا پہلے سے اندازہ لگانا اور ان کے لیے تیاری کرنا۔" },
      { id: "b16_a6", en: "Drive or ride.", ur: "گاڑی یا موٹر سائیکل چلانا۔" },
      { id: "b16_a7", en: "Move things from one place to another.", ur: "چیزوں کو ایک جگہ سے دوسری جگہ پہنچانا۔" },
    ],
    personalQualities: [
      { id: "b16_q1", en: "Realistic", ur: "حقیقت پسند" },
      { id: "b16_q2", en: "Mechanical", ur: "مشینی سوجھ بوجھ" },
      { id: "b16_q3", en: "Coordinated", ur: "اچھا تال میل" },
      { id: "b16_q4", en: "Observant", ur: "غور سے مشاہدہ کرنا" },
      { id: "b16_q5", en: "Planner", ur: "منصوبہ بندی کی صلاحیت" },
    ],
    schoolSubjects: [
      { id: "b16_s1", en: "Math", ur: "ریاضی" },
      { id: "b16_s2", en: "Trade and Industry courses", ur: "ہنر اور صنعت کے کورسز (ووکیشنل)" },
      { id: "b16_s3", en: "Physical Sciences", ur: "طبیعی علوم (فزکس، کیمسٹری)" },
      { id: "b16_s4", en: "Economics", ur: "معاشیات" },
      { id: "b16_s5", en: "Foreign Language", ur: "غیر ملکی زبان" },
    ]
  }
];
